# Change these first
owner: jcortell # Your GitHub username
repo: uptime # Your GitHub repository name
user-agent: jcortell

# Add your sites here
sites:
  - name: Kanteron Website
    url: https://www.kanteron.com/
  - name: Kanteron Sitio Web
    url: https://web.kanteron.com/
  - name: Kanteron Blog
    url: https://blog.kanteron.com/
  - name: Blog de Kanteron
    url: https://bloges.kanteron.com/
  - name: Jorge Website
    url: https://jorge.cortell.net/
  - name: Jorge Sitio Web
    url: https://web.cortell.net/
  - name: Jorge Blog
    url: https://blog.cortell.net/
  - name: Blog de Jorge
    url: https://bloges.cortell.net/
  - name: Hugo Website
    url: https://hugo.cortell.net/
  - name: DolceVita Seas Website
    url: https://www.dolcevitaseas.com/
  - name: CruiseCurator Website (redirects to Virtuoso)
    url: https://www.virtuoso.com/advisor/stepseri33810/advisors/16133810/stephanie-serino
    
assignees: # Users to assign downtime issues (optional)
  - jcortell

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://blog.kanteron.com/images/logo.png
  name: Uptime
  introTitle: "**Uptime** automatic monitor and status page, powered entirely by GitHub."
  introMessage: This status page uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages.
#  navbar:
#    - title: Status
#      href: /
#    - title: GitHub
#      href: https://github.com/jcortell/uptime

# Previous line used to say       href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
